# Generated by Django 4.0 on 2023-11-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_recommendedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='recommended_course',
            field=models.TextField(),
        ),
    ]
