# Generated by Django 4.0 on 2023-11-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_predresults_cet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendedCourse',
        ),
    ]
