# Generated by Django 4.0 on 2023-11-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_recommendedcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prediction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.predresults')),
            ],
        ),
    ]
