# Generated by Django 4.0 on 2023-10-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cet', models.FloatField()),
                ('gpa', models.FloatField()),
                ('strand', models.CharField(max_length=200)),
                ('recommended_course', models.CharField(max_length=30)),
            ],
        ),
    ]
