# Generated by Django 4.0 on 2023-10-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='strand',
            field=models.CharField(choices=[('2', 'Science, Technology, Engineering, and Mathematics (STEM)'), ('1', 'Humanities and Social Sciences (HUMSS)'), ('3', 'Technology Vocational and Livelihood (TVL)'), ('0', 'General Academic Strand (GAS)'), ('4', 'Accountancy, Business, and Management (ABM)')], max_length=1),
        ),
    ]
