# Generated by Django 4.0 on 2023-11-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_predresults_strand'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='predresults',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
