# Generated by Django 4.0 on 2023-11-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_predresults_first_name_predresults_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='last_name',
        ),
    ]
