# Generated by Django 4.0 on 2023-11-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_recommendedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='strand',
            field=models.CharField(choices=[('0', 'Accountancy, Business, and Management (ABM)'), ('1', 'General Academic Strand (GAS)'), ('2', 'Humanities and Social Sciences (HUMSS)'), ('3', 'Sports Track (SP)'), ('4', 'Science, Technology, Engineering, and Mathematics (STEM)'), ('5', 'Technology Vocational and Livelihood (TVL)'), ('6', 'Arts & Design (AD)')], max_length=1),
        ),
    ]
