# Generated by Django 4.0 on 2023-11-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_recommendedcourse_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedcourse',
            name='percentage',
            field=models.CharField(max_length=155),
        ),
    ]
